### ISSUE TITLE
[Bug] Not Found schedmd-slurm-gcp-v7-partition 

### ISSUE THREAD

**Issue by Aryido** [GoogleCloudPlatform/scientific-computing-examples#99]
While following the steps from the official documentation [Llama 2 Fine-tuning with Slurm](https://cloud.google.com/cluster-toolkit/docs/machine-learning/llama2-finetuning-slurm), I encountered a failure with the error message:
```
community/modules/compute/schedmd-slurm-gcp-v7-partition not found.
```

<img width="1512" alt="Screenshot 2024-10-08 at 2 44 06 PM" src="https://github.com/user-attachments/assets/c0cbaa99-1d23-49ff-8292-42946734eb4d">

I checked the repository at [GoogleCloudPlatform/cluster-toolkit](https://github.com/GoogleCloudPlatform/cluster-toolkit/tree/main/community/modules/compute), and it seems that the v7 version is not available yet.

It looks like this hasn’t been updated.

# Possible Solutions
- Create the v7 module.
- Roll back the hpc-slurm-llama2.yaml to use the v6 version.

**Comment by jrossthomson** [comment]
This should be corrected now.
